# This is a basic workflow to help you get started with Actions

name: Build Nginx

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'nginx/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'nginx/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build ./nginx --file ./nginx/Dockerfile --tag ghcr.io/${{ github.repository }}/windows-exporter-nginx:0.0.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to Registry
        run: docker push ghcr.io/${{ github.repository }}/windows-exporter-nginx:0.0.1